<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [1]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [26]:
array1 = np.arange(10)
print(f"El array es: {array1}")

El array es: [0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [24]:
array2 = np.reshape(array1, (2, 5))
print(f"El array es: \n{array2} \ncon dimensiones: \n{array2.shape}")

El array es: 
[[0 1 2 3 4]
 [5 6 7 8 9]] 
con dimensiones: 
(2, 5)


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [32]:
array3 = np.array([0, 2, 0, 3, 0, 4, 0])

print(f" Los elementos son {array3[array3 != 0]}, con índices {np.where(array3 > 0)[0]}")

 Los elementos son [2 3 4], con índices [1 3 5]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [38]:
array4 = np.random.rand(3, 3)
print(F"El array es: \n{array4}")

El array es: 
[[0.24288524 0.19180557 0.88581255]
 [0.40300994 0.08988497 0.79962586]
 [0.00699524 0.76052388 0.33963664]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [44]:
array5 = np.random.rand(10)

print(f"El array es: \n{array5} \ncuyo valor máximo es {round(array5.max(), 4)} y valor mínimo {round(array5.min(), 4)}")

El array es: 
[0.77711739 0.01724741 0.07716797 0.89524055 0.05393919 0.3945182
 0.82993756 0.01958319 0.91054968 0.65669012] 
cuyo valor máximo es 0.9105 y valor mínimo 0.0172


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [46]:
array6 = np.random.rand(10)

print(f"El array es \n{array6} \nmientras que el array invertido es: \n{array6[::-1]}")

El array es 
[0.88096989 0.84526255 0.12174435 0.2156439  0.22766084 0.64386015
 0.51421335 0.408387   0.90424344 0.37726767] 
mientras que el array invertido es: 
[0.37726767 0.90424344 0.408387   0.51421335 0.64386015 0.22766084
 0.2156439  0.12174435 0.84526255 0.88096989]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [77]:
array7 = np.random.randint(14, 24, (2, 3, 4))

print(f"El array es: \n{array7}")

# Todas las posiciones donde vale 15
posiciones = np.where(array7 == 15)

# Si hay coincidencias, obtener la primera
if posiciones[0].size > 0:
    primera_posicion = tuple(pos[0] for pos in posiciones)
    print(f"La primera ocurrencia de 15 está en: {primera_posicion}")
else:
    print("No se encontró ningún 15 en el array.")

# Elementos del primer array
print(f"\nLos elementos del primer array son: \n{array7[0]}")

# Última fila del último array
print(f"\nLa última fila del último array es: \n{array7[-1,-1,:]}")


El array es: 
[[[23 19 16 22]
  [16 20 20 15]
  [23 17 20 19]]

 [[18 17 18 23]
  [16 19 16 18]
  [21 18 16 17]]]
La primera ocurrencia de 15 está en: (0, 1, 3)

Los elementos del primer array son: 
[[23 19 16 22]
 [16 20 20 15]
 [23 17 20 19]]

La última fila del último array es: 
[21 18 16 17]



#### Ejercicio 8 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [85]:
array8 = np.random.randint(1, 31, (3, 2, 5))

print(f"El array es: \n{array8}")
print(f"\nSubarray con los dos primeros elementos de cada fila del primer array: \n{array8[0,:,:2]}")
print(f"\nSubarray que contiene todas las filas de los dos últimos arrays: \n{array8[-2:,:,:]}")

El array es: 
[[[14  7 23 15 16]
  [19  9 10  1 20]]

 [[11 21 26 10 19]
  [21 22 10  6  1]]

 [[25 30  3 28 15]
  [14  7 12 23 11]]]

Subarray con los dos primeros elementos de cada fila del primer array: 
[[14  7]
 [19  9]]

Subarray que contiene todas las filas de los dos últimos arrays: 
[[[11 21 26 10 19]
  [21 22 10  6  1]]

 [[25 30  3 28 15]
  [14  7 12 23 11]]]


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [88]:
array9 = np.random.randint(1, 24, (4, 3, 2))

print(f"El array es: \n{array9}")

array9[1,1,:] = 0
print(f"\nCambiar todos los elementos de la segunda fila del segundo array por 0: \n{array9}")
array9[-1,:,:] = -1
print(f"\nCambiar todos los valores del último array a -1: \n{array9}")

El array es: 
[[[20 12]
  [ 3  1]
  [ 3 12]]

 [[15  6]
  [18 20]
  [ 8 18]]

 [[ 5  7]
  [ 3 13]
  [11 16]]

 [[20  1]
  [ 3  8]
  [23 22]]]

Cambiar todos los elementos de la segunda fila del segundo array por 0: 
[[[20 12]
  [ 3  1]
  [ 3 12]]

 [[15  6]
  [ 0  0]
  [ 8 18]]

 [[ 5  7]
  [ 3 13]
  [11 16]]

 [[20  1]
  [ 3  8]
  [23 22]]]

Cambiar todos los valores del último array a -1: 
[[[20 12]
  [ 3  1]
  [ 3 12]]

 [[15  6]
  [ 0  0]
  [ 8 18]]

 [[ 5  7]
  [ 3 13]
  [11 16]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 10 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [90]:
array10 = np.random.randint(-10, 13, (2, 4, 3))

print(f"El array es: \n{array10}")
print(f"\nSeleccionar elementos mayores a 5: \n{array10[array10 > 5]}")
array10[array10 < 0] = 0
print(f"\nReemplazar los negativos por 0: \n{array10}")

El array es: 
[[[  3  -9  -3]
  [  1  -3  -9]
  [  8  -7  -8]
  [ -5  -8   8]]

 [[ 11 -10  -2]
  [ 11   7  12]
  [ -2   1   1]
  [ -1  12  11]]]

Seleccionar elementos mayores a 5: 
[ 8  8 11 11  7 12 12 11]

Reemplazar los negativos por 0: 
[[[ 3  0  0]
  [ 1  0  0]
  [ 8  0  0]
  [ 0  0  8]]

 [[11  0  0]
  [11  7 12]
  [ 0  1  1]
  [ 0 12 11]]]


#### Ejercicio 11 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [97]:
array11 = np.random.randint(1, 28, (3, 3, 3))

print(f"El array es: \n{array11}")
print(f"\nSeleccionar subarray del segundo array con solo las 2 primeras columnas: \n{array11[1, :, :2]}")
print(f"\nSeleccionar elementos del tercer array mayores a 20: \n{array11[2][array11[2] > 20]}")

El array es: 
[[[23 16 13]
  [ 5 18  5]
  [ 2 24 20]]

 [[ 1  1 14]
  [20 14  4]
  [ 6  9  1]]

 [[ 4 22 14]
  [20 23 12]
  [ 1  9 14]]]

Seleccionar subarray del segundo array con solo las 2 primeras columnas: 
[[ 1  1]
 [20 14]
 [ 6  9]]

Seleccionar elementos del tercer array mayores a 20: 
[22 23]


#### Ejercicio 12 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [113]:
array12 = np.random.randint(-100, 100, (10))

print(f"El array es: \n{array12}")

print(f"El máximo es {array12.max()}")
print(f"El máximo es {array12.min()}")

array12[array12 == array12.max()] = 0
array12[array12 == array12.min()] = 0

print(f"\nEl array final es: \n{array12}")

El array es: 
[  9 -37 -89 -48  16  30 -14  71  -5 -44]
El máximo es 71
El máximo es -89

El array final es: 
[  9 -37   0 -48  16  30 -14   0  -5 -44]


#### Ejercicio 13 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [115]:
array13 = np.random.randint(1, 100, (15))

print(f"El array es: \n{array13}")
print(f"El array ordenado es: \n{np.sort(array13)}")

El array es: 
[36 68 52 94  6 20 28 55 21 53 27 22 77 96 34]
El array ordenado es: 
[ 6 20 21 22 27 28 34 36 52 53 55 68 77 94 96]


#### Ejercicio 14 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [124]:
array14 = np.random.randint(1, 5, (4, 4))

print(f"El array es: \n{array14}")
print(f"La suma a lo largo de las filas es: \n{array14.sum(axis = 1)}")
print(f"La suma a lo largo de las columnas es: \n{array14.sum(axis = 0)}")

El array es: 
[[1 2 3 1]
 [2 2 4 2]
 [1 2 4 4]
 [4 3 4 4]]
La suma a lo largo de las filas es: 
[ 7 10 11 15]
La suma a lo largo de las columnas es: 
[ 8  9 15 11]


#### Ejercicio 15 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [135]:
# Creamos una de 1
array15 = np.ones((5, 5))
# Rellenamos el interior con 0
array15[1:4, 1:4] = 0

print(f"El array es: \n{array15}")

El array es: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 16 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [146]:
array16 = np.random.randint(1, 20, (10))

print(f"El array es: \n{array16}")
print(f"La media es: \n{array16.mean()}")
print(f"La desviación típica es: \n{round(array16.std(), 2)}")

El array es: 
[ 5 10  1  4  8 11 17 14  2  9]
La media es: 
8.1
La desviación típica es: 
4.91


#### Ejercicio 17 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [147]:
array17 = np.random.randint(1, 24, (2, 3, 4))

print(f"El array es: \n{array17}")
print(f"El array traspuesto es: \n{array17.transpose(2,1,0)}")

El array es: 
[[[17 10  6 14]
  [16 20  7 11]
  [10 14 19 18]]

 [[ 7 21 19 16]
  [ 3 22  9 14]
  [17  3  8 21]]]
El array traspuesto es: 
[[[17  7]
  [16  3]
  [10 17]]

 [[10 21]
  [20 22]
  [14  3]]

 [[ 6 19]
  [ 7  9]
  [19  8]]

 [[14 16]
  [11 14]
  [18 21]]]


Inicialmente tenemos 2 matrices de 3 filas y 4 columnas (2,3,4)
Tras la transposición tenemos 4 matrices de 3 filas y 2 columnas (4,3,2)

#### Ejercicio 18 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [152]:
array18 = np.random.randint(1, 24, (3, 4, 2))

print(f"El array es: \n{array18}")
print(f"El array traspuesto es: \n{array18.transpose(1,0,2)}")
print(f"Lo podemos comprobar usando shape: {array18.transpose(1,0,2).shape}")

El array es: 
[[[10 18]
  [23 22]
  [ 3 18]
  [18 18]]

 [[ 6 11]
  [ 3 14]
  [15 13]
  [ 5 15]]

 [[11 11]
  [16 14]
  [13  3]
  [22 13]]]
El array traspuesto es: 
[[[10 18]
  [ 6 11]
  [11 11]]

 [[23 22]
  [ 3 14]
  [16 14]]

 [[ 3 18]
  [15 13]
  [13  3]]

 [[18 18]
  [ 5 15]
  [22 13]]]
Lo podemos comprobar usando shape: (4, 3, 2)


#### Ejercicio 19 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [157]:
array19 = np.random.randint(1, 24, (3, 2, 4))
print(f"El array es: \n{array19}")

# Rotamos el 0 con el 1 (3 con 2) -> (2, 3, 4)
first_rotation = array19.swapaxes(0, 1)
# Rotamos el 0 con el 2 (2 con 4) -> (4, 3, 2)
print(f"El resultado es: {first_rotation.swapaxes(0, 2)}")
print(f"Lo podemos comprobar usando shape: {first_rotation.swapaxes(0, 2).shape}")

El array es: 
[[[ 5 21  9  9]
  [ 1  5  7  4]]

 [[23 10 10 23]
  [19 19  6  2]]

 [[13 11 19  8]
  [ 1  7 14 19]]]
El resultado es: [[[ 5  1]
  [23 19]
  [13  1]]

 [[21  5]
  [10 19]
  [11  7]]

 [[ 9  7]
  [10  6]
  [19 14]]

 [[ 9  4]
  [23  2]
  [ 8 19]]]
Lo podemos comprobar usando shape: (4, 3, 2)


#### Ejercicio 20 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [162]:
array20 = np.random.randint(-10, 10, (3, 4, 5))
print(f"El array inicial es: \n{array20}")

empty_array = np.zeros_like(array20)
print(f"El array vacío (ceros) es: \n{empty_array}")

El array inicial es: 
[[[  0   4  -7  -2   4]
  [  7   0  -8  -3   6]
  [-10  -3  -2   7  -8]
  [ -4   9  -5 -10  -6]]

 [[ -6  -7   5   7  -6]
  [  3  -6  -9   6   0]
  [ -4  -6  -9  -9  -3]
  [  0   1   5   2  -3]]

 [[ -5  -9  -4   3   1]
  [ -7  -4   6   6   3]
  [  3  -5  -4   8   4]
  [  8  -5 -10   7  -8]]]
El array vacío (ceros) es: 
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [171]:
median = np.median(array20)
print(f"La mediana es: {median}")

print(f"\nEl array con la mediana sustituida es: \n{np.where(array20 == median, "M", array20)}")

La mediana es: -3.0

El array con la mediana sustituida es: 
[[['0' '4' '-7' '-2' '4']
  ['7' '0' '-8' 'M' '6']
  ['-10' 'M' '-2' '7' '-8']
  ['-4' '9' '-5' '-10' '-6']]

 [['-6' '-7' '5' '7' '-6']
  ['3' '-6' '-9' '6' '0']
  ['-4' '-6' '-9' '-9' 'M']
  ['0' '1' '5' '2' 'M']]

 [['-5' '-9' '-4' '3' '1']
  ['-7' '-4' '6' '6' '3']
  ['3' '-5' '-4' '8' '4']
  ['8' '-5' '-10' '7' '-8']]]


In [172]:
print(f"\nEl array con los valores mayores a la mediana sustituidos: \n{np.where(array20 > median, "X", array20)}")


El array con los valores mayores a la mediana sustituidos: 
[[['X' 'X' '-7' 'X' 'X']
  ['X' 'X' '-8' '-3' 'X']
  ['-10' '-3' 'X' 'X' '-8']
  ['-4' 'X' '-5' '-10' '-6']]

 [['-6' '-7' 'X' 'X' '-6']
  ['X' '-6' '-9' 'X' 'X']
  ['-4' '-6' '-9' '-9' '-3']
  ['X' 'X' 'X' 'X' '-3']]

 [['-5' '-9' '-4' 'X' 'X']
  ['-7' '-4' 'X' 'X' 'X']
  ['X' '-5' '-4' 'X' 'X']
  ['X' '-5' '-10' 'X' '-8']]]


In [174]:
print(f"\nEl array con los valores menores a la mediana sustituidos: \n{np.where(array20 < median, "Y", array20)}")


El array con los valores menores a la mediana sustituidos: 
[[['0' '4' 'Y' '-2' '4']
  ['7' '0' 'Y' '-3' '6']
  ['Y' '-3' '-2' '7' 'Y']
  ['Y' '9' 'Y' 'Y' 'Y']]

 [['Y' 'Y' '5' '7' 'Y']
  ['3' 'Y' 'Y' '6' '0']
  ['Y' 'Y' 'Y' 'Y' '-3']
  ['0' '1' '5' '2' '-3']]

 [['Y' 'Y' 'Y' '3' '1']
  ['Y' 'Y' '6' '6' '3']
  ['3' 'Y' 'Y' '8' '4']
  ['8' 'Y' 'Y' '7' 'Y']]]


In [175]:
maximo = np.max(array20)
print(f"El máximo es: {maximo}")

print(f"\nEl array el máximo sustituido es: \n{np.where(array20 == maximo, "MAX", array20)}")

El máximo es: 9

El array el máximo sustituido es: 
[[['0' '4' '-7' '-2' '4']
  ['7' '0' '-8' '-3' '6']
  ['-10' '-3' '-2' '7' '-8']
  ['-4' 'MAX' '-5' '-10' '-6']]

 [['-6' '-7' '5' '7' '-6']
  ['3' '-6' '-9' '6' '0']
  ['-4' '-6' '-9' '-9' '-3']
  ['0' '1' '5' '2' '-3']]

 [['-5' '-9' '-4' '3' '1']
  ['-7' '-4' '6' '6' '3']
  ['3' '-5' '-4' '8' '4']
  ['8' '-5' '-10' '7' '-8']]]


In [177]:
minimo = np.min(array20)
print(f"El máximo es: {minimo}")

print(f"\nEl array el máximo sustituido es: \n{np.where(array20 == minimo, "MIN", array20)}")

El máximo es: -10

El array el máximo sustituido es: 
[[['0' '4' '-7' '-2' '4']
  ['7' '0' '-8' '-3' '6']
  ['MIN' '-3' '-2' '7' '-8']
  ['-4' '9' '-5' 'MIN' '-6']]

 [['-6' '-7' '5' '7' '-6']
  ['3' '-6' '-9' '6' '0']
  ['-4' '-6' '-9' '-9' '-3']
  ['0' '1' '5' '2' '-3']]

 [['-5' '-9' '-4' '3' '1']
  ['-7' '-4' '6' '6' '3']
  ['3' '-5' '-4' '8' '4']
  ['8' '-5' 'MIN' '7' '-8']]]


#### Ejercicio 21 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [196]:
array21 = np.random.randint(-1, 1, (4, 4))

print(f"El array inicial es: \n{array21}")

El array inicial es: 
[[-1 -1  0  0]
 [-1 -1 -1 -1]
 [-1 -1  0  0]
 [-1 -1  0  0]]


In [199]:
# Recorremos filas
for i in range(4):

    # Recorremos columnas
    for j in range(4):

        iguales = True

        # Comprobamos 
        for k in range(4):

            if array21[i][k] != array21[k][j]:
                iguales = False
                break

        if iguales:
            print(f"La fila {i} y la columna {j} son iguales.")

La fila 1 y la columna 0 son iguales.
La fila 1 y la columna 1 son iguales.
